server:
  port: 8087

spring:
  datasource:
    username: ${DB_USER:delivery_db}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:delivery_db}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: false
        order_inserts: true
        jdbc.batch_size: 100
        ddl-auto: validate
        validator:
          fail_fast: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history_delivery
  rabbitmq:
    username: ${MQ_USER:rabbit-mq}
    password: ${MQ_PASSWORD:rabbit-mq}
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}

logging:
  level:
    com:
      rabbitmq:
        client: debug
    org:
      springframework:
        amqp: debug
        retry: debug
      hibernate:
        type: trace
        stat: debug
        orm:
          jdbc:
            bind: trace

rabbitmq:
  exchange:
    name: amq.topic
  processed-routing-key:
    name: message.order.events
  queue:
    name: "*.delivery.events"

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true